### ISSUE TITLE
NGR Sync Is Down

### ISSUE THREAD

**Issue by jins-agridigital** [fullprofile/agridigital-status-monitor#15]
The NGR Sync is currently experiencing an outage. We are currently investigating

**Comment by mrjk05** [comment]
We are currently restarting some of our internal services

**Comment by mrjk05** [comment]
We have restarted our internal services and currently undertaking testing of the NGR sync on customer records

**Comment by mrjk05** [comment]
We have verified that the NGR sync is now operational and working as expected
