### ISSUE TITLE
Synchronisation Outage on List Screens - Degraded service

### ISSUE THREAD

**Issue by sandylewisau** [fullprofile/agridigital-status-monitor#29]
We are currently experiencing issues with our List Screen Synchronisation. Our engineers are currently working on a solution and we thank you for your patience. Please contact support for further assistance.

**Comment by SG2019** [comment]
We are currently experiencing issues with our List Screen Synchronisation. Our engineers are currently working on a solution and we thank you for your patience. Please contact support for further assistance.
