### ISSUE TITLE
Scheduled Maintenance - Thursday 25 August between 9pm and 10pm

### ISSUE THREAD

**Issue by SG2019** [fullprofile/agridigital-status-monitor#55]

**Comment by SG2019** [comment]
We're upgrading our login screens ahead of harvest. Whilst the change should be instantaneous from the old to the new, there could be a small window where users can't access the login page. Please contact support if you encounter an issue. Thank you for your patience.

**Comment by sandylewisau** [comment]
Maintenance and testing has now been completed. Please contact support if you encounter an issue. Thank you for your patience.
